2024-08-26 19:53:04 align.main INFO : Reading netlist: /home/adair/Documents/CAD/characterization_script_sandbox_rundir/cm_ota/cm_ota.sp subckt=CM_OTA, flat=0
2024-08-26 19:53:04 align.compiler.compiler INFO : Starting topology identification...
2024-08-26 19:53:05 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/cmdline.py", line 197, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/main.py", line 167, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/compiler.py", line 84, in compiler_input
    ckt_data = create_data.read_inputs(design_name)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/create_database.py", line 33, in read_inputs
    assert top_subckt, f"{name.upper()} not found in library {[e.name for e in self.lib]}"
AssertionError: CM_OTA not found in library ['NMOS', 'PMOS', 'CAP', 'RES', 'IND', 'SKY130_FD_PR__PFET_01V8', 'SKY130_FD_PR__NFET_01V8', 'CURRENT_MIRROR_OTA']
