2024-08-26 19:28:32 align.main INFO : Reading netlist: /home/adair/Documents/CAD/characterization_script_sandbox_rundir/cm_ota/cm_ota.sp subckt=CM_OTA, flat=0
2024-08-26 19:28:32 align.compiler.compiler INFO : Starting topology identification...
2024-08-26 19:28:32 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/util.py", line 235, in get_generator
    module = importlib.import_module(pdk_dir_stem)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ALIGN-pdk-sky130'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/cmdline.py", line 197, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/main.py", line 167, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/compiler.py", line 72, in compiler_input
    ckt_parser = read_models(pdk_dir, config_path)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/read_library.py", line 17, in read_models
    pdk_models = get_generator('pdk_models', pdk_dir)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/util.py", line 248, in get_generator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/adair/Documents/CAD/align/ALIGN-public/ALIGN-pdk-sky130/primitive.py'
